# Generated by Django 5.1.1 on 2024-09-20 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
    ]
