# Generated by Django 5.1.1 on 2024-09-22 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0003_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["seat"]},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("journey", "seat")},
        ),
    ]
